deployment: b
syncStream: sync2

deploymentSettings:
  a:
    isSyncSource: true
    fileExchangeEnabled: true
    fileExchangeConfig:
      incomingDir: /data/in
      outgoingDir: /data/out

defaultSettings:
  ackTimeout: 5s
  ackRetryJitter: 0.2
  ackRetryStep: 5s
  ackRetryMax: 60s
  heartbeatInterval: 60s
  pendingAcksMax: 10
  pendingIncomingMessagesDeleteThreshold: 40
  pendingIncomingMessagesMaxBuffered: 100
  maxAccumulatedPayloadSize: 4_194_304 # 4MB
  natsOperationTimeout: 5s
  batchFlushTimeout: 0.2s
  exchangeOperationTimeout: 5s
  fileExchangeConfig:
    pollingStartDelay: 0s
    pollingInterval: 1m
    pollingRetryInterval: 30s
