volumes:
  nats-dataA:
  nats-dataB:
  file-outA:
  file-inA:

networks:
  netA:
  netB:

services:
  sync_a:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      SYNC_LOG_LEVEL: debug-3
      SYNC_NATS_URLS: nats://nats_a:4222
      SYNC_CONFIG_FILE: /config/configA.yml
    volumes:
      - "./:/config/:ro"
      - file-inA:/data/in
      - file-outA:/data/out
    networks:
      - netA
    ports:
      - 8900:8900

  nats_a:
    image: ${NATS_IMAGE}
    command: --debug
      --name natsA
      --jetstream
      --store_dir /data
    volumes:
      - nats-dataA:/data
    ports:
      - "4222:4222"
    networks:
      - netA

  sync_b:
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      SYNC_LOG_LEVEL: debug-3
      SYNC_NATS_URLS: nats://nats_b:4222
      SYNC_CONFIG_FILE: /config/configB.yml
    volumes:
      - "./:/config/:ro"
      - file-inA:/data/out # reverse direction
      - file-outA:/data/in # reverse direction
    networks:
      - netB
    ports:
      - 8901:8900

  nats_b:
    image: ${NATS_IMAGE}
    command: --debug
      --name natsB
      --jetstream
      --store_dir /data
    volumes:
      - nats-dataB:/data
    ports:
      - "4322:4222" # non-standard port
    networks:
      - netB
